name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # 安装依赖
      - run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # 自动提升补丁版本号
      - name: Bump version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version)
          echo "New version is $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      # 提交新的 package.json
      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to $NEW_VERSION"
          git push --force  # 强制推送

      # 创建 git tag
      - name: Create git tag
        run: |
          git tag "v$NEW_VERSION"
          git push origin "v$NEW_VERSION"

      # 发布 npm 包
      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
